name: Release Versioning Workflow

run-name: "Release Versioning Workflow"

on:
    workflow_dispatch:
        inputs:
            action:
                type: choice
                description: Version To Increment (If Custom. Please Input Release or Development Version Below) 
                options:
                    - Major
                    - Minor
                    - Patch
                    - Custom
                required: true
            release_version:
                type: string
                description: Name of release. May follow SemVer (Major.Minor.Patch) format
            development_version:
                type: string
                description: Name of next development version. Must follow SemVer + "-" + <TEXT> (Major.Minor.Patch-TEXT) format

jobs:
    get_input:
       name: Get Input
       runs-on: ubuntu-latest
       steps:
        - name: Checkout Codebase
          uses: actions/checkout@v4.1.7
        - name: Downloading Java
          uses: actions/setup-java@v4 
          with:
                java-version: '21'
                distribution: 'adopt'
        - name: Build Project
          run: mvn clean install